# Generated by Django 5.2 on 2025-04-12 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('web', 'web'), ('text', 'text'), ('video', 'video'), ('image', 'image'), ('design', 'design'), ('programming', 'programming'), ('other', 'other'), ('all', 'all')], default='OTHER', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills', models.CharField(choices=[('html', 'html'), ('css', 'css'), ('js', 'js'), ('php', 'php'), ('python', 'python'), ('java', 'java'), ('other', 'other'), ('all', 'all')], default='OTHER', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
