# Generated by Django 5.2 on 2025-04-13 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_user_task_creator_task_executor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('web', 'web'), ('text', 'text'), ('video', 'video'), ('image', 'image'), ('design', 'design'), ('programming', 'programming'), ('other', 'other'), ('all', 'all')], default='OTHER', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'created_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TakedTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taked_tasks', to='tasks.createdtask')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taked_tasks',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
