# Generated by Django 5.2 on 2025-04-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_createdtask_takedtask_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takedtask',
            old_name='created_task',
            new_name='task',
        ),
    ]
