version: '3.9'

services:
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: base.txt
    command: sh -c "/entrypoint-web.sh"
    ports:
      - "8002:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db-data:
